### PR TITLE
feat(docuploader): add destination-prefix option

### PR DESCRIPTION
**Pull request by tbpg**
The prefix option will be used when uploading DocFX YAML. We need to
distinguish HTML docs vs DocFX YAML. Then, another job will convert the
YAML to HTML. This way, all DocFX tarballs can start with `docfx-` and we can
strip that prefix when uploading the resulting HTML.

### CODE REVIEW

**Comment by tmatsuo** [comment]
I'm not sure if it's a good idea to have this option.

Instead can we always upload html files?

**Comment by JustinBeckwith** [comment]
I *love* this idea.  One of the original goals was to try getting to an intermediary format that could be re-generated into HTML as the template on cloudsite changes.  By storing this in YAML instead of HTML, we can re-generate any time we want with different visuals.

**Comment by tmatsuo** [comment]
I'm not opposed to have a capability of only re-generating the HTML from yaml files.

I don't feel quite right to have this option and metadata.

How about just to have `--destination-prefix` option?

**Comment by tmatsuo** [comment]
I may miss the big picture, so I could be convinced if there's a reason to add `format` metadata.

**Comment by tbpg** [comment]
I switched it to `--destination-prefix`.

The risk of this is that each client library will be responsible for setting the right `docfx` prefix. Typos will not be caught when calling the tool -- only when docs don't show up. We also need to be consistent in how the prefix is applied, so we can remove it in the HTML generation job.

**Pull request merged**
